/**
 * @fileoverview Externs for preactRouter generated by generate-closure-externs in browser runtime
 * @see https://gist.github.com/tripolskypetr/ed33439520b59c5077cbdf5d0ff4ea62
 * @externs
 */
var preactRouter = {
  subscribers: function () {},
  getCurrentUrl: function () {},
  route: function () {},
  Router: {
    constructor: function () {},
    shouldComponentUpdate: function () {},
    canRoute: function () {},
    routeTo: function () {},
    componentWillMount: function () {},
    componentDidMount: function () {},
    componentWillUnmount: function () {},
    componentWillUpdate: function () {},
    componentDidUpdate: function () {},
    getMatchingChildren: function () {},
    render: function () {},
  },
  Route: function () {},
  Link: function () {},
  exec: function () {},
};
