/**
 * @fileoverview Externs for preact generated by generate-closure-externs in browser runtime
 * @see https://gist.github.com/tripolskypetr/ed33439520b59c5077cbdf5d0ff4ea62
 * @externs
 */

/** 
 * TODO: place your custom JSX factory callbacks
 * @interface
 */
var atrributes = {
  onCopy: function() {},
  onCut: function() {},
  onPaste: function() {},
  onKeyDown: function() {},
  onKeyPress: function() {},
  onKeyUp: function() {},
  onFocus: function() {},
  onBlur: function() {},
  onChange: function() {},
  onInput: function() {},
  onSubmit: function() {},
  onClick: function() {},
  onDoubleClick: function() {},
  onDrag: function() {},
  onDragEnd: function() {},
  onDragEnter: function() {},
  onDragExit: function() {},
  onDragLeave: function() {},
  onDragOver: function() {},
  onDragStart: function() {},
  onDrop: function() {},
  onMouseDown: function() {},
  onMouseEnter: function() {},
  onMouseLeave: function() {},
  onMouseMove: function() {},
  onMouseUp: function() {},
  onTouchCancel: function() {},
  onTouchEnd: function() {},
  onTouchMove: function() {},
  onTouchStart: function() {},
  onScroll: function() {},
  onWheel: function() {},
};

var preact = {
  render: function () {},
  hydrate: function () {},
  createElement: function () {},
  Fragment: function () {},
  createRef: function () {},
  isValidElement: function () {},
  h: function (type, /** @implements {atrributes} */ props, children) {},
  Component: {
    setState: function () {},
    forceUpdate: function () {},
    render: function () {},
  },
  cloneElement: function () {},
  createContext: function () {},
  toChildArray: function () {},
  _e: function () {},
  options: {
    __e: function () {},
    __r: function () {},
    diffed: function () {},
    __c: function () {},
    unmount: function () {},
    vnode: function () {},
    __b: function () {},
    _diff: function () {},
    _commit: function () {},
    __: function () {},
    __h: function () {},
  },
};
