/**
 * @fileoverview Externs for preactHooks generated by generate-closure-externs in browser runtime
 * @see https://gist.github.com/tripolskypetr/ed33439520b59c5077cbdf5d0ff4ea62
 * @externs
 */
var preactHooks = {
  useState: function () {},
  useReducer: function () {},
  useEffect: function () {},
  useLayoutEffect: function () {},
  useRef: function () {},
  useImperativeHandle: function () {},
  useMemo: function () {},
  useCallback: function () {},
  useContext: function () {},
  useDebugValue: function () {},
  useErrorBoundary: function () {},
};
