/**
 * @fileoverview Externs for typestyle generated by generate-closure-externs in browser runtime
 * @see https://gist.github.com/tripolskypetr/ed33439520b59c5077cbdf5d0ff4ea62
 * @externs
 */
var typestyle = {
  TypeStyle: {
    _afterAllSync: function () {},
    _getTag: function () {},
    _styleUpdated: function () {},
    style: function () {},
  },
  types: function () {},
  extend: function () {},
  classes: function () {},
  media: function () {},
  setStylesTarget: function () {},
  cssRaw: function () {},
  cssRule: function () {},
  forceRenderStyles: function () {},
  fontFace: function () {},
  getStyles: function () {},
  keyframes: function () {},
  reinit: function () {},
  style: function () {},
  stylesheet: function () {},
  createTypeStyle: function () {},
};
