/**
 * @fileoverview Typedefs for M generated by generate-typescript-entries in browser runtime
 * @see https://gist.github.com/tripolskypetr/b9c56202cd98935a49389fb46f77ef19
 */
declare namespace M {
  export function jQueryLoaded(...args: any): any;
  export function tabPressed(...args: any): any;
  export function keyDown(...args: any): any;
  export function initializeJqueryWrapper(...args: any): any;
  export function AutoInit(...args: any): any;
  export function objectSelectorString(...args: any): any;
  export function guid(...args: any): any;
  export function escapeHash(...args: any): any;
  export function elementOrParentIsFixed(...args: any): any;
  export function checkWithinContainer(...args: any): any;
  export function checkPossibleAlignments(...args: any): any;
  export function getOverflowParent(...args: any): any;
  export function getIdFromTrigger(...args: any): any;
  export function getDocumentScrollTop(...args: any): any;
  export function getDocumentScrollLeft(...args: any): any;
  export function throttle(...args: any): any;
  export function anime(...args: any): any;
  export function Collapsible(...args: any): any;
  export function Dropdown(...args: any): any;
  export function Modal(...args: any): any;
  export function Materialbox(...args: any): any;
  export function Parallax(...args: any): any;
  export function Tabs(...args: any): any;
  export function Tooltip(...args: any): any;
  export function Toast(...args: any): any;
  export function toast(...args: any): any;
  export function Sidenav(...args: any): any;
  export function ScrollSpy(...args: any): any;
  export function Autocomplete(...args: any): any;
  export function updateTextFields(...args: any): any;
  export function validate_field(...args: any): any;
  export function textareaAutoResize(...args: any): any;
  export function Slider(...args: any): any;
  export function Chips(...args: any): any;
  export function Pushpin(...args: any): any;
  export function FloatingActionButton(...args: any): any;
  export function Datepicker(...args: any): any;
  export function Timepicker(...args: any): any;
  export function CharacterCounter(...args: any): any;
  export function Carousel(...args: any): any;
  export function TapTarget(...args: any): any;
  export function FormSelect(...args: any): any;
  export function Range(...args: any): any;
}
